"""CTD-style PDF reporting helpers."""

from __future__ import annotations

import datetime as dt
import io
import re
from html import escape
from pathlib import Path
from typing import Any


LABELS = {
    "ko": {
        "title": "CTD 품질 및 불순물 검토 보고서",
        "subtitle": "ToxiGuard-Platform Ver.1 | CTD Quality & Impurity Review",
        "generated": "생성일",
        "confidential": "검토용 문서 | Decision-support only",
        "disclaimer": "본 보고서는 의사결정 보조용 prototype 산출물이며, 공식 규제기관 판정 또는 검증된 시스템 산출물이 아닙니다. 최종 판단은 원문 CTD와 분야별 전문가 검토로 확인해야 합니다.",
        "application_snapshot": "1. 신청 및 문서 개요",
        "executive_summary": "2. 종합 요약",
        "development_story": "3. 개발 서사 및 관리전략",
        "product_context": "4. 제품 및 제형 정보",
        "ctd_evidence": "5. CTD 근거 맵",
        "spec_method": "6. 기준 및 시험방법 검토",
        "performance": "7. 용출 / 생동성 근거",
        "stability": "8. 안정성 검토",
        "impurity": "9. 물질 / 불순물 / ICH M7 검토",
        "sources": "10. 규제 기준 출처 연결",
        "deficiencies": "11. 보완사항 추적",
        "integrated": "12. 종합 평가",
        "appendix": "부록. 상세 추출 근거",
        "product": "제품명",
        "active": "주성분",
        "strength": "함량",
        "dosage": "제형",
        "route": "투여경로",
        "application_type": "신청 유형",
        "application_number": "신청 번호",
        "applicant": "신청사",
        "review_status": "검토 상태",
        "review_cycle": "검토 차수",
        "discipline_owner": "검토 분야",
        "recommendation": "권고 조치",
        "rationale": "근거",
        "key_issues": "주요 검토 이슈",
        "residual_uncertainty": "잔여 불확실성",
        "not_detected": "해당 자료에서 명확한 근거가 추출되지 않았습니다.",
        "none": "없음",
        "source": "출처",
        "reviewer_check": "검토자 확인사항",
        "evidence_summary": "근거 요약",
        "page": "페이지",
        "ctd_anchor": "CTD 위치",
        "status": "상태",
        "issue": "이슈",
        "severity": "중요도",
        "ir_wording": "보완 요청 문구",
        "detected": "확인됨",
        "gap": "추가 확인 필요",
    },
    "en": {
        "title": "CTD Quality and Impurity Review Report",
        "subtitle": "ToxiGuard-Platform Ver.1 | CTD Quality & Impurity Review",
        "generated": "Generated",
        "confidential": "Review document | Decision-support only",
        "disclaimer": "This report is a prototype decision-support output. It is not an official regulatory determination or a validated system output. Final conclusions require verification against the source CTD and discipline reviewer judgment.",
        "application_snapshot": "1. Application and Document Overview",
        "executive_summary": "2. Executive Summary",
        "development_story": "3. Development Story and Control Strategy",
        "product_context": "4. Product and Formulation Context",
        "ctd_evidence": "5. CTD Evidence Map",
        "spec_method": "6. Specification and Test Method Review",
        "performance": "7. Dissolution / Bioequivalence Evidence",
        "stability": "8. Stability Review",
        "impurity": "9. Compound / Impurity / ICH M7 Review",
        "sources": "10. Regulatory Source Crosswalk",
        "deficiencies": "11. Deficiency Tracker",
        "integrated": "12. Integrated Assessment",
        "appendix": "Appendix. Detailed Extracted Evidence",
        "product": "Product",
        "active": "Active Substance",
        "strength": "Strength",
        "dosage": "Dosage Form",
        "route": "Route",
        "application_type": "Application Type",
        "application_number": "Application Number",
        "applicant": "Applicant",
        "review_status": "Review Status",
        "review_cycle": "Review Cycle",
        "discipline_owner": "Discipline Owner",
        "recommendation": "Recommended Action",
        "rationale": "Rationale",
        "key_issues": "Key Review Issues",
        "residual_uncertainty": "Residual Uncertainty",
        "not_detected": "No clear evidence was extracted from the current source.",
        "none": "None",
        "source": "Source",
        "reviewer_check": "Reviewer Check",
        "evidence_summary": "Evidence Summary",
        "page": "Page",
        "ctd_anchor": "CTD Anchor",
        "status": "Status",
        "issue": "Issue",
        "severity": "Severity",
        "ir_wording": "Information Request Wording",
        "detected": "Detected",
        "gap": "Needs confirmation",
    },
}

COMMON_KO_TERMS = {
    "Acceptable With Expert Confirmation": "전문가 확인 후 수용 가능",
    "Information Request Needed": "보완 요청 필요",
    "In Review": "검토 중",
    "Information Request": "보완 요청",
    "Adequate": "적합",
    "Not Adequate": "부적합",
    "Needs review": "검토 필요",
    "Open": "진행 중",
    "Closed": "종결",
    "No information request proposed by the prototype.": "Prototype 기준으로 제안된 보완 요청은 없습니다.",
    "No blocking deficiency generated by prototype rules": "Prototype 규칙에서 중대한 보완사항이 생성되지 않았습니다.",
    "source-document verification by discipline reviewer": "분야별 검토자의 원문 확인 필요",
    "proposed specifications and analytical control strategy": "제안 기준 및 분석 관리전략",
    "analytical or dissolution method rationale": "분석법 또는 용출법 설정 근거",
    "stability and packaging support": "안정성 및 포장 근거",
    "Prototype review did not identify blocking quality or ICH M7 concerns.": "Prototype 검토에서는 품질 또는 ICH M7 관점의 중대한 차단 이슈가 확인되지 않았습니다.",
    "Direct Evidence": "직접 근거",
    "Product Name": "제품명",
    "Active Substance": "주성분",
    "Strength": "함량",
    "Dosage Form": "제형",
    "Route": "투여경로",
    "Confirm against final submitted CTD source.": "최종 제출 CTD 원문과 대조 확인 필요.",
    "Confirm amount, grade, function, compatibility, and regulatory acceptability.": "사용량, 등급, 기능, 배합 적합성 및 규제 적합성 확인 필요.",
    "Confirm strength, salt form, and grade against 3.2.P.1 / 3.2.P.2.": "함량, 염 형태, 등급을 3.2.P.1 / 3.2.P.2와 대조 확인 필요.",
    "Active substance / API": "주성분 / API",
    "Binder": "결합제",
    "Disintegrant": "붕해제",
    "Lubricant": "활택제",
    "Filler / binder": "부형제 / 결합제",
    "Document Analyzer candidate compound": "문서 분석에서 감지된 후보 물질",
    "Molecule Screening / Reference Impurity Lookup": "분자 스크리닝 / 참조 불순물 조회",
    "Product context extraction": "제품 정보 추출",
    "Packaging / Container Closure": "포장 / 용기마개 시스템",
    "Storage / Stability Condition": "보관 / 안정성 조건",
    "Stability Evidence": "안정성 근거",
}


REPORT_COLUMN_LABELS = {
    "항목 / Test": "Test",
    "세부항목 / Sub-test": "Sub-test",
    "기준 / Specification": "Specification",
    "시험방법 / Test Method": "Test Method",
    "자료위치 / Source": "Source",
    "검토메모 / Reviewer Note": "Reviewer Note",
    "시험항목 / Test Item": "Test Item",
    "기준 / Acceptance Criteria": "Acceptance Criteria",
    "기준 출처 / Specification Source": "Specification Source",
    "표준액 농도 / Standard Solution": "Standard Solution",
    "검액 농도 / Sample Solution": "Sample Solution",
    "시험방법 출처 / Method Source": "Method Source",
    "CTD 위치 / CTD Anchor": "CTD Anchor",
    "상태 / Status": "Status",
    "검토 포인트 / Reviewer Focus": "Reviewer Focus",
    "동등성 항목 / Equivalence Item": "Equivalence Item",
    "MFDS Writing Heading": "MFDS Writing Heading",
    "항목": "Field",
    "값": "Value",
    "성분": "Ingredient",
    "역할": "Role",
    "근거": "Evidence",
    "물질명": "Name",
    "연결 검토": "Linked Review",
    "정보 유형": "Context Type",
    "추출값": "Extracted Value",
}


def create_pdf_report(payload: dict, language: str = "en") -> bytes:
    """Create a CTD-style regulatory assessment PDF."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.cidfonts import UnicodeCIDFont
        from reportlab.pdfbase.ttfonts import TTFont
        from reportlab.platypus import (
            KeepTogether,
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        return _minimal_pdf_stub(payload)

    language = "ko" if language == "ko" else "en"
    label = LABELS[language]
    font_name, bold_font = _register_report_fonts(pdfmetrics, TTFont, UnicodeCIDFont, language)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.62 * inch,
        rightMargin=0.62 * inch,
        topMargin=0.72 * inch,
        bottomMargin=0.62 * inch,
        title=label["title"],
        author="ToxiGuard-Platform Ver.1",
    )

    styles = _build_styles(getSampleStyleSheet(), ParagraphStyle, font_name, bold_font, colors, TA_CENTER, TA_LEFT)
    story: list[Any] = []
    context = payload.get("product_context") or {}
    profile = payload.get("application_snapshot") or {}
    worksheet = payload.get("fda_style_reviewer_worksheet") or {}
    integrated = _worksheet_item(worksheet, "Integrated Assessment")

    story.extend(_cover_page(payload, profile, context, integrated, styles, label, Table, TableStyle, colors, language))
    story.append(PageBreak())

    story.extend(_section(label["application_snapshot"], styles, label))
    story.append(
        _key_value_table(
            [
                (label["application_type"], profile.get("application_type")),
                (label["application_number"], profile.get("application_number")),
                (label["applicant"], profile.get("applicant")),
                (label["review_cycle"], profile.get("review_cycle")),
                (label["discipline_owner"], profile.get("discipline_owner")),
                (label["review_status"], profile.get("review_status")),
            ],
            styles,
            Table,
            TableStyle,
            colors,
        )
    )

    story.extend(_section(label["executive_summary"], styles, label))
    story.append(_para(_executive_narrative(payload, worksheet, label, language), styles["Body"]))
    story.append(Spacer(1, 8))
    story.append(
        _key_value_table(
            [
                (label["recommendation"], _localize(integrated.get("Recommended Action"), language)),
                (label["key_issues"], integrated.get("Key Review Issues")),
                (label["residual_uncertainty"], integrated.get("Residual Uncertainty")),
                (label["rationale"], integrated.get("Rationale")),
            ],
            styles,
            Table,
            TableStyle,
            colors,
        )
    )

    story.extend(_development_story_section(payload, context, worksheet, styles, label, Table, TableStyle, colors))
    story.extend(_product_context_section(context, styles, label, Table, TableStyle, colors))
    story.extend(_document_extraction_section(payload, styles, label, Table, TableStyle, colors))
    story.extend(_ctd_evidence_section(worksheet, styles, label, Table, TableStyle, colors))
    story.extend(_specification_section(payload, worksheet, styles, label, Table, TableStyle, colors))
    story.extend(_signal_section(label["performance"], payload.get("bioequivalence"), styles, label, "bioequivalence"))
    story.extend(_bioequivalence_calculation_section(payload, styles, label, Table, TableStyle, colors))
    story.extend(_signal_section(label["stability"], payload.get("stability"), styles, label, "stability"))
    story.extend(_impurity_section(payload, context, worksheet, styles, label, Table, TableStyle, colors))
    story.extend(_sources_section(payload, styles, label, Table, TableStyle, colors))
    story.extend(_deficiency_section(worksheet, styles, label, Table, TableStyle, colors))
    story.extend(_integrated_section(worksheet, styles, label, Table, TableStyle, colors))
    story.extend(_appendix_section(payload, styles, label, Table, TableStyle, colors))
    story.append(Spacer(1, 10))
    story.append(_para(label["disclaimer"], styles["FinePrint"]))

    def on_page(canvas, doc_obj):
        _draw_header_footer(canvas, doc_obj, label, colors, font_name, bold_font)

    def on_cover(canvas, doc_obj):
        _draw_cover_footer(canvas, doc_obj, label, colors, font_name)

    doc.build(story, onFirstPage=on_cover, onLaterPages=on_page)
    return buffer.getvalue()


def _register_report_fonts(pdfmetrics, TTFont, UnicodeCIDFont, language: str) -> tuple[str, str]:
    if language == "ko":
        for font_path in [
            "/System/Library/Fonts/Supplemental/AppleGothic.ttf",
            "/System/Library/Fonts/AppleSDGothicNeo.ttc",
        ]:
            if Path(font_path).exists():
                try:
                    pdfmetrics.registerFont(TTFont("ToxiKorean", font_path))
                    return "ToxiKorean", "ToxiKorean"
                except Exception:
                    continue
        try:
            pdfmetrics.registerFont(UnicodeCIDFont("HYSMyeongJo-Medium"))
            pdfmetrics.registerFont(UnicodeCIDFont("HYGothic-Medium"))
            return "HYSMyeongJo-Medium", "HYGothic-Medium"
        except Exception:
            pass
    return "Helvetica", "Helvetica-Bold"


def _build_styles(base, ParagraphStyle, font_name, bold_font, colors, TA_CENTER, TA_LEFT) -> dict:
    styles = {
        "CoverTitle": ParagraphStyle(
            "CoverTitle",
            parent=base["Title"],
            fontName=bold_font,
            fontSize=22,
            leading=28,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#102033"),
            spaceAfter=10,
        ),
        "CoverSubtitle": ParagraphStyle(
            "CoverSubtitle",
            parent=base["Normal"],
            fontName=font_name,
            fontSize=10.5,
            leading=14,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#536273"),
        ),
        "Section": ParagraphStyle(
            "Section",
            parent=base["Heading2"],
            fontName=bold_font,
            fontSize=13,
            leading=17,
            textColor=colors.HexColor("#102033"),
            borderWidth=0,
            borderPadding=0,
            spaceBefore=14,
            spaceAfter=8,
        ),
        "Subsection": ParagraphStyle(
            "Subsection",
            parent=base["Heading3"],
            fontName=bold_font,
            fontSize=10.3,
            leading=13,
            textColor=colors.HexColor("#155E75"),
            spaceBefore=8,
            spaceAfter=5,
        ),
        "Body": ParagraphStyle(
            "Body",
            parent=base["BodyText"],
            fontName=font_name,
            fontSize=8.9,
            leading=12.2,
            alignment=TA_LEFT,
            textColor=colors.HexColor("#1F2937"),
        ),
        "TableHead": ParagraphStyle(
            "TableHead",
            parent=base["BodyText"],
            fontName=bold_font,
            fontSize=7.8,
            leading=9.5,
            textColor=colors.white,
        ),
        "TableCell": ParagraphStyle(
            "TableCell",
            parent=base["BodyText"],
            fontName=font_name,
            fontSize=7.3,
            leading=9,
            textColor=colors.HexColor("#1F2937"),
        ),
        "Key": ParagraphStyle(
            "Key",
            parent=base["BodyText"],
            fontName=bold_font,
            fontSize=7.8,
            leading=9.5,
            textColor=colors.HexColor("#334155"),
        ),
        "FinePrint": ParagraphStyle(
            "FinePrint",
            parent=base["Italic"],
            fontName=font_name,
            fontSize=7,
            leading=9,
            textColor=colors.HexColor("#667085"),
        ),
        "Badge": ParagraphStyle(
            "Badge",
            parent=base["BodyText"],
            fontName=bold_font,
            fontSize=7,
            leading=8,
            textColor=colors.HexColor("#155E75"),
        ),
    }
    return styles


def _cover_page(payload, profile, context, integrated, styles, label, Table, TableStyle, colors, language: str) -> list:
    from reportlab.platypus import Spacer

    product = context.get("product_name") or profile.get("product_name") or "TBD"
    active = context.get("active_substance") or "TBD"
    generated = f"{dt.datetime.utcnow():%Y-%m-%d %H:%M UTC}"
    meta_rows = [
        (label["product"], product),
        (label["active"], active),
        (label["strength"], context.get("strength") or "TBD"),
        (label["dosage"], context.get("dosage_form") or profile.get("dosage_form") or "TBD"),
        (label["route"], context.get("route") or profile.get("route") or "TBD"),
        (label["recommendation"], _localize(integrated.get("Recommended Action") or "TBD", language)),
        (label["generated"], generated),
    ]
    logo = Table(
        [[_para("TG", styles["CoverTitle"])]],
        colWidths=[72],
        rowHeights=[72],
        style=[
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#102033")),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#102033")),
        ],
    )
    return [
        Spacer(1, 40),
        logo,
        Spacer(1, 18),
        _para(label["title"], styles["CoverTitle"]),
        _para(label["subtitle"], styles["CoverSubtitle"]),
        Spacer(1, 28),
        _key_value_table(meta_rows, styles, Table, TableStyle, colors),
        Spacer(1, 26),
        _para(label["disclaimer"], styles["FinePrint"]),
    ]


def _section(title: str, styles: dict, label: dict) -> list:
    from reportlab.platypus import KeepTogether

    return [KeepTogether([_para(title, styles["Section"]), _rule()])]


def _product_context_section(context, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["product_context"], styles, label)
    ko = _is_ko(label)
    basic = context.get("basic_info") or []
    linked = context.get("linked_substances") or []
    formulation = context.get("formulation") or []
    package_storage = context.get("package_storage") or []
    story.append(_rows_table(_normalize_basic_rows(basic, label), ["항목" if _is_ko(label) else "Field", "값" if _is_ko(label) else "Value", label["reviewer_check"]], styles, Table, TableStyle, colors, [1.25, 2.2, 2.3]))
    story.append(_subheading("제형 / 조성" if ko else "Formulation / Composition", styles))
    formulation_rows = _rename_rows(
        formulation,
        {"Ingredient": "성분", "Role": "역할", "Evidence": "근거", "Reviewer Check": label["reviewer_check"]},
        ko,
    )
    story.append(_rows_table(_limit_rows(formulation_rows, 8), ["성분", "역할", "근거", label["reviewer_check"]] if ko else ["Ingredient", "Role", "Evidence", label["reviewer_check"]], styles, Table, TableStyle, colors, [1.45, 1.25, 2.15, 1.45]))
    story.append(_subheading("연결 물질" if ko else "Linked Substances", styles))
    linked_rows = _rename_rows(
        linked,
        {"Name": "물질명", "Role": "역할", "SMILES": "SMILES", "Linked Review": "연결 검토"},
        ko,
    )
    story.append(_rows_table(_limit_rows(linked_rows, 6), ["물질명", "역할", "SMILES", "연결 검토"] if ko else ["Name", "Role", "SMILES", "Linked Review"], styles, Table, TableStyle, colors, [1.35, 1.35, 2.3, 1.25]))
    story.append(_subheading("포장 / 보관" if ko else "Packaging / Storage", styles))
    package_rows = _rename_rows(
        package_storage,
        {"Context Type": "정보 유형", "Extracted Value": "추출값", "Evidence": "근거", "Linked Review": "연결 검토"},
        ko,
    )
    story.append(_rows_table(_limit_rows(package_rows, 5), ["정보 유형", "추출값", "근거", "연결 검토"] if ko else ["Context Type", "Extracted Value", "Evidence", "Linked Review"], styles, Table, TableStyle, colors, [1.3, 1.35, 2.5, 1.1]))
    return story


def _document_extraction_section(payload, styles, label, Table, TableStyle, colors) -> list:
    from reportlab.platypus import Spacer

    story = _section("4A. Document Extraction Quality" if not _is_ko(label) else "4A. 문서 추출 품질", styles, label)
    profile = payload.get("document_profile") or {}
    project_documents = payload.get("project_documents") or []
    project_summaries = payload.get("project_document_summaries") or []
    signal_details = payload.get("signal_details") or {}
    evidence_blocks = payload.get("evidence_blocks") or []
    signal_rows = []
    for category in ["specifications", "test_methods", "bioequivalence", "stability", "compounds"]:
        rows = signal_details.get(category, []) if isinstance(signal_details, dict) else []
        pages = sorted({str(row.get("Page", "")) for row in rows if row.get("Page", "") not in {"", "N/A"}})
        signal_rows.append(
            {
                "Signal Category": category.replace("_", " ").title(),
                "Detected Signals": len(rows),
                "Evidence Pages": ", ".join(pages[:8]) if pages else "N/A",
                "Review Interpretation": _signal_interpretation(category, rows, label),
            }
        )
    summary_rows = [
        ("Project Name", payload.get("project_name") or "N/A"),
        ("Project Documents", len(project_documents) or "N/A"),
        ("Document Type", profile.get("document_type") or "N/A"),
        ("Source CTD Section", profile.get("source_ctd_section") or "N/A"),
        ("Evidence Blocks", len(evidence_blocks)),
        ("Specification Table Rows", len(payload.get("specification_table") or [])),
    ]
    story.append(_key_value_table(summary_rows, styles, Table, TableStyle, colors))
    story.append(Spacer(1, 5))
    if project_documents:
        story.append(_subheading("프로젝트 문서함" if _is_ko(label) else "Project Dossier", styles))
        story.append(
            _rows_table(
                _limit_rows(project_documents, 12),
                ["Document", "Source", "Type", "Pages", "Characters", "Warnings"],
                styles,
                Table,
                TableStyle,
                colors,
                [1.8, 0.75, 1.3, 0.55, 0.8, 0.65],
            )
        )
        if project_summaries:
            story.append(_subheading("문서별 신호 요약" if _is_ko(label) else "Per-Document Signal Summary", styles))
            story.append(
                _rows_table(
                    _limit_rows(project_summaries, 12),
                    ["Document", "Specifications", "Test Methods", "Bioequivalence", "Stability", "Compounds"],
                    styles,
                    Table,
                    TableStyle,
                    colors,
                    [1.9, 0.85, 0.85, 0.9, 0.75, 0.75],
                )
            )
        story.append(Spacer(1, 5))
    story.append(
        _rows_table(
            signal_rows,
            ["Signal Category", "Detected Signals", "Evidence Pages", "Review Interpretation"],
            styles,
            Table,
            TableStyle,
            colors,
            [1.25, 0.65, 1.25, 3.15],
        )
        )
    return story


def _bioequivalence_calculation_section(payload, styles, label, Table, TableStyle, colors) -> list:
    result = payload.get("bioequivalence_f2_result") or {}
    if not result:
        return []

    ko = _is_ko(label)
    title = "6A. f2 / Bootstrap 용출 유사성 계산" if ko else "6A. f2 / Bootstrap Dissolution Similarity"
    story = _section(title, styles, label)
    story.append(
        _key_value_table(
            [
                ("f2 Similarity Factor" if not ko else "f2 유사성인자", result.get("f2")),
                ("Bootstrap 95% CI" if not ko else "Bootstrap 95% 신뢰구간", f"{result.get('ci_low')} - {result.get('ci_high')}"),
                ("Bootstrap Median" if not ko else "Bootstrap 중앙값", result.get("bootstrap_median")),
                ("P(f2 >= 50)" if not ko else "P(f2 ≥ 50)", f"{result.get('probability_f2_ge_50')}%"),
                ("CV Check" if not ko else "CV 점검", result.get("cv_flag")),
                ("FDA-style Decision" if not ko else "FDA-style 판단", result.get("fda_decision")),
                ("Next Action" if not ko else "다음 검토", result.get("fda_next_action")),
            ],
            styles,
            Table,
            TableStyle,
            colors,
        )
    )

    profile_rows = payload.get("bioequivalence_profile_summary") or []
    if profile_rows:
        story.append(_subheading("Reference/Test Dissolution Profile" if not ko else "대조약/시험약 용출 프로파일", styles))
        story.append(
            _rows_table(
                _limit_rows(profile_rows, 12),
                [
                    "Time (min)",
                    "Reference Mean (%)",
                    "Test Mean (%)",
                    "Difference (%)",
                    "Reference CV (%)",
                    "Test CV (%)",
                ],
                styles,
                Table,
                TableStyle,
                colors,
                [0.75, 1.25, 1.2, 1.0, 1.15, 1.15],
            )
        )
    return story


def _ctd_evidence_section(worksheet, styles, label, Table, TableStyle, colors) -> list:
    rows = _worksheet_item(worksheet, "Submission Map")
    story = _section(label["ctd_evidence"], styles, label)
    story.append(
        _rows_table(
            _limit_rows(rows, 12),
            ["eCTD Section", "Evidence Extract", "Source Location", "Disposition"],
            styles,
            Table,
            TableStyle,
            colors,
            [1.45, 2.9, 1.05, 0.9],
        )
    )
    return story


def _executive_narrative(payload, worksheet, label, language: str) -> str:
    if language != "ko":
        narrative = payload.get("document_narrative")
        if narrative:
            return narrative
        context = payload.get("product_context") or {}
        product = context.get("product_name") or "the product"
        active = context.get("active_substance") or "the active substance"
        counts = _signal_counts(payload)
        detected = [name for name, count in counts.items() if count]
        integrated = _worksheet_item(worksheet, "Integrated Assessment")
        recommendation = _localize(integrated.get("Recommended Action") or "Needs review", language)
        if detected:
            evidence_phrase = ", ".join(detected)
        else:
            evidence_phrase = "limited extractable CTD evidence"
        return (
            f"This review frames {product} ({active}) as a CTD evidence package rather than a list of isolated excerpts. "
            f"The extracted evidence currently supports review of {evidence_phrase}. "
            f"The preliminary recommendation is '{recommendation}', subject to source-document verification and discipline reviewer judgment. "
            "The report is organized in the same technical sequence used in development dossiers: product identity, formulation and process rationale, control strategy, performance evidence, stability, impurity risk, and reviewer actions."
        )

    counts = {
        "기준": len(payload.get("specifications") or []),
        "시험방법": len(payload.get("test_methods") or []),
        "생동성/용출": len(payload.get("bioequivalence") or []),
        "안정성": len(payload.get("stability") or []),
        "ICH M7": len(payload.get("screening_results") or []),
    }
    detected = [name for name, count in counts.items() if count]
    missing = [name for name, count in counts.items() if not count]
    integrated = _worksheet_item(worksheet, "Integrated Assessment")
    recommendation = _localize(integrated.get("Recommended Action") or "검토 필요", language)
    parts = [
        f"현재 문서에서는 {', '.join(detected) if detected else '명확한 CTD 신호'} 항목이 추출되었습니다.",
        f"권고 조치는 '{recommendation}'이며, 이는 원문 CTD와 분야별 검토자의 확인을 전제로 합니다.",
    ]
    if missing:
        parts.append(f"{', '.join(missing)} 항목은 추가 원문 확인 또는 보완자료 확인이 필요합니다.")
    parts.append("아래 섹션은 제품/제형 정보, 기준 및 시험방법, 생동성/용출, 안정성, 불순물/ICH M7, 규제 기준 출처 순서로 재정렬되었습니다.")
    return " ".join(parts)


def _specification_section(payload, worksheet, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["spec_method"], styles, label)
    spec_rows = payload.get("specification_table") or _worksheet_item(worksheet, "Specification Table")
    if spec_rows:
        story.append(
            _rows_table(
                _limit_rows(spec_rows, 14),
                ["항목 / Test", "세부항목 / Sub-test", "기준 / Specification", "시험방법 / Test Method", "CTD Anchor"],
                styles,
                Table,
                TableStyle,
                colors,
                [1.25, 1.25, 1.65, 1.55, 0.9],
            )
        )
    else:
        story.append(_bullet_list(payload.get("specifications"), styles, label, limit=10))
    story.append(_subheading("Analytical Procedure / Validation", styles))
    story.append(_bullet_list(payload.get("test_methods"), styles, label, limit=10))
    return story


def _development_story_section(payload, context, worksheet, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["development_story"], styles, label)
    ko = _is_ko(label)
    language = "ko" if ko else "en"
    story.append(_para(_development_story_narrative(payload, context, worksheet, language), styles["Body"]))
    story.append(_subheading("개발 문서 흐름" if ko else "Dossier Storyline", styles))
    story.append(
        _rows_table(
            _dossier_storyline_rows(payload, context, label),
            ["구간" if ko else "Stage", "문서가 말하는 내용" if ko else "What the dossier should explain", "ToxiGuard 검토 초점" if ko else "ToxiGuard review focus"],
            styles,
            Table,
            TableStyle,
            colors,
            [1.1, 2.8, 2.1],
        )
    )
    story.append(_subheading("관리전략 요약" if ko else "Control Strategy Snapshot", styles))
    story.append(
        _rows_table(
            _control_strategy_rows(payload, context, worksheet, label),
            ["검토 축" if ko else "Review Axis", "현재 근거" if ko else "Current Evidence", "확인할 질문" if ko else "Reviewer Question"],
            styles,
            Table,
            TableStyle,
            colors,
            [1.25, 2.35, 2.4],
        )
    )
    return story


def _signal_section(title: str, items, styles, label, key: str) -> list:
    story = _section(title, styles, label)
    story.append(_bullet_list(items, styles, label, limit=10))
    return story


def _development_story_narrative(payload, context, worksheet, language: str) -> str:
    product = context.get("product_name") or "TBD"
    active = context.get("active_substance") or "TBD"
    dosage = context.get("dosage_form") or "TBD"
    route = context.get("route") or "TBD"
    counts = _signal_counts(payload)
    integrated = _worksheet_item(worksheet, "Integrated Assessment")
    recommendation = _localize(integrated.get("Recommended Action") or ("검토 필요" if language == "ko" else "Needs review"), language)
    if language == "ko":
        return (
            f"본 검토는 {product}의 개발 자료를 제품 정체성, 제형/제조 근거, 기준 및 시험방법, 성능 근거, 안정성, 불순물 위험 순서로 재구성했습니다. "
            f"현재 추출된 신호는 기준 {counts['specifications']}건, 시험방법 {counts['test_methods']}건, 생동성/용출 {counts['bioequivalence']}건, "
            f"안정성 {counts['stability']}건, 물질/불순물 {counts['compounds']}건입니다. "
            f"주성분은 {active}, 제형/투여경로는 {dosage}/{route}로 추출되었으며, 권고 조치는 '{recommendation}'입니다. "
            "아래 표는 원문 개발자료의 이야기 흐름을 심사자가 확인해야 할 관리전략 질문으로 바꾼 것입니다."
        )
    return (
        f"This report reorganizes the {product} dossier around a development narrative: product identity, formulation and process rationale, "
        f"specification and analytical controls, performance evidence, stability support, and impurity risk. "
        f"The current extraction identified {counts['specifications']} specification signal(s), {counts['test_methods']} test-method signal(s), "
        f"{counts['bioequivalence']} dissolution/bioequivalence signal(s), {counts['stability']} stability signal(s), and {counts['compounds']} compound/impurity signal(s). "
        f"The extracted active substance is {active}, with dosage form/route recorded as {dosage}/{route}. "
        f"The preliminary action is '{recommendation}'."
    )


def _dossier_storyline_rows(payload, context, label) -> list[dict]:
    ko = _is_ko(label)
    rows = []
    def row(stage, story, focus):
        if ko:
            rows.append({"구간": stage, "문서가 말하는 내용": story, "ToxiGuard 검토 초점": focus})
        else:
            rows.append({"Stage": stage, "What the dossier should explain": story, "ToxiGuard review focus": focus})

    product = context.get("product_name") or "TBD"
    active = context.get("active_substance") or "TBD"
    formulation_count = len(context.get("formulation") or [])
    if ko:
        row("제품 정체성", f"{product} / {active}의 제품명, 주성분, 함량, 제형, 투여경로를 먼저 고정합니다.", "제품 기본정보가 CTD 본문, 표지, 기준 및 시험방법 표와 일치하는지 확인")
        row("제형/제조 근거", f"제형 및 첨가제 근거 {formulation_count}건을 개발 배경과 연결합니다.", "조성, 기능, 제조공정, scale-up 또는 보관 조건의 연결성 확인")
        row("기준 및 시험방법", "시험항목별 기준, 시험방법, 표준액/검액 농도, 계산식을 한 표로 묶습니다.", "Specification과 method가 서로 대응되는지 확인")
        row("성능/안정성", "용출/동등성, 안정성, 포장/보관 근거를 제품 성능 유지 논리로 연결합니다.", "f2, bootstrap, shelf-life, container closure 근거 확인")
        row("위험/보완사항", "불순물, 유전독성, 출처 기준, 잔여 불확실성을 보완 요청 언어로 전환합니다.", "USP/EP/ICH/MFDS 근거와 reviewer action 확인")
    else:
        row("Product Identity", f"Fix the identity of {product} / {active}: product name, strength, dosage form, and route.", "Confirm consistency across cover page, CTD body, and specification tables.")
        row("Formulation / Process Rationale", f"Link {formulation_count} formulation or excipient item(s) to development rationale.", "Check composition, function, manufacturing rationale, scale-up, and storage linkage.")
        row("Specification / Method", "Keep each test item paired with acceptance criteria, procedure, standard/sample concentration, and calculation logic.", "Confirm that every specification has a matching analytical method and source anchor.")
        row("Performance / Stability", "Connect dissolution, equivalence, stability, packaging, and storage evidence to product performance.", "Review f2/bootstrap, shelf-life, and container-closure support.")
        row("Risk / Deficiency", "Translate impurity, genotoxicity, regulatory-source, and uncertainty findings into reviewer actions.", "Confirm USP/EP/ICH/MFDS basis and information-request wording.")
    return rows


def _control_strategy_rows(payload, context, worksheet, label) -> list[dict]:
    ko = _is_ko(label)
    details = payload.get("signal_details") or {}
    integrated = _worksheet_item(worksheet, "Integrated Assessment")
    def count(key):
        direct = payload.get(key) or []
        detailed = details.get(key) if isinstance(details, dict) else []
        return max(len(direct), len(detailed or []))
    def evidence(key, fallback):
        value = count(key)
        if ko:
            return f"{value}건 감지" if value else fallback
        return f"{value} signal(s) detected" if value else fallback
    rows = []
    def row(axis, current, question):
        if ko:
            rows.append({"검토 축": axis, "현재 근거": current, "확인할 질문": question})
        else:
            rows.append({"Review Axis": axis, "Current Evidence": current, "Reviewer Question": question})

    if ko:
        row("제품/제형", f"제품정보 {len(context.get('basic_info') or [])}건, formulation {len(context.get('formulation') or [])}건", "주성분, 함량, 제형, 첨가제 기능이 제출자료 전체에서 일관적인가?")
        row("기준 및 시험방법", evidence("specifications", "명확한 기준 근거 부족") + " / " + evidence("test_methods", "시험방법 근거 부족"), "각 시험항목에 기준, 방법, 시스템적합성, 표준액/검액 농도가 대응되는가?")
        row("성능/동등성", evidence("bioequivalence", "용출/동등성 근거 부족"), "대조약 대비 용출률, f2, bootstrap 또는 동등성 판단 근거가 충분한가?")
        row("안정성", evidence("stability", "안정성 근거 부족"), "가속/장기/포장 조건이 shelf-life와 직접 연결되는가?")
        row("불순물/유전독성", evidence("compounds", "물질/불순물 근거 부족"), "관련물질, degradation, ICH M7/QSAR 근거와 관리한도가 설명되는가?")
        row("종합 판단", _localize(integrated.get("Recommended Action") or "검토 필요", "ko"), "잔여 불확실성이 보완 요청 또는 reviewer language로 정리되었는가?")
    else:
        row("Product / Formulation", f"{len(context.get('basic_info') or [])} identity item(s); {len(context.get('formulation') or [])} formulation item(s)", "Are active substance, strength, dosage form, and excipient functions consistent across the dossier?")
        row("Specification / Method", evidence("specifications", "No clear specification evidence") + " / " + evidence("test_methods", "No clear method evidence"), "Does each test item have criteria, procedure, system suitability, and standard/sample concentration?")
        row("Performance / Equivalence", evidence("bioequivalence", "No clear dissolution/equivalence evidence"), "Is reference-drug dissolution, f2, bootstrap, or equivalence rationale sufficient?")
        row("Stability", evidence("stability", "No clear stability evidence"), "Do accelerated/long-term/package conditions directly support shelf life?")
        row("Impurity / Genotoxicity", evidence("compounds", "No clear compound/impurity evidence"), "Are related substances, degradation, ICH M7/QSAR basis, and control limits explained?")
        row("Integrated Decision", _localize(integrated.get("Recommended Action") or "Needs review", "en"), "Are residual uncertainties translated into reviewer language or information requests?")
    return rows


def _signal_counts(payload) -> dict[str, int]:
    details = payload.get("signal_details") or {}
    counts = {}
    for key in ["specifications", "test_methods", "bioequivalence", "stability", "compounds"]:
        direct = payload.get(key) or []
        detailed = details.get(key) if isinstance(details, dict) else []
        counts[key] = max(len(direct), len(detailed or []))
    return counts


def _impurity_section(payload, context, worksheet, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["impurity"], styles, label)
    language = "ko" if _is_ko(label) else "en"
    linked = context.get("linked_substances") or []
    screening = payload.get("genotoxicity_tool_result") or payload.get("screening_results") or _worksheet_item(worksheet, "ICH M7 Review")
    qsar_validation = payload.get("qsar_validation_result") or []
    qsar_sources = payload.get("qsar_reference_sources") or []
    story.append(_subheading("Detected / Linked Compounds", styles))
    story.append(_rows_table(_limit_rows(linked, 8), ["Name", "Role", "SMILES", "Source"], styles, Table, TableStyle, colors, [1.45, 1.35, 2.35, 1.15]))
    story.append(_subheading("ICH M7 Screening Summary", styles))
    story.append(
        _rows_table(
            _limit_rows(screening, 10),
            _preferred_columns(
                screening,
                ["Compound", "SMILES", "ICH M7 Class", "Risk Score", "QSAR Package Status", "QSAR Confidence", "Alerts", "Reviewer Action"],
            ),
            styles,
            Table,
            TableStyle,
            colors,
        )
    )
    if qsar_validation:
        story.append(_subheading("QSAR Model Validation Matrix", styles))
        story.append(
            _rows_table(
                _limit_rows(qsar_validation, 14),
                ["Compound", "Validation Criterion", "Status", "Current Evidence", "Reviewer Action", "Reference Source"],
                styles,
                Table,
                TableStyle,
                colors,
                [1.0, 1.35, 0.55, 2.0, 1.6, 1.0],
            )
        )
    if qsar_sources:
        story.append(_subheading("QSAR Reference Sources", styles))
        story.append(
            _rows_table(
                _limit_rows(qsar_sources, 6),
                ["Source", "Reference Focus", "Use in Matrix"],
                styles,
                Table,
                TableStyle,
                colors,
                [1.0, 2.8, 2.2],
            )
        )
    narrative = payload.get("regulatory_narrative")
    if narrative:
        story.append(_para(_report_text(narrative, language, 900), styles["Body"]))
    return story


def _sources_section(payload, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["sources"], styles, label)
    rows = payload.get("regulatory_source_crosswalk") or []
    story.append(
        _rows_table(
            _limit_rows(rows, 8),
            ["Signal Category", "Detected Signals", "Primary CTD / Review Anchor", "Primary Standards", "Reviewer Use"],
            styles,
            Table,
            TableStyle,
            colors,
            [1.25, 0.65, 1.35, 1.55, 1.55],
        )
    )
    matches = payload.get("regulatory_source_matches") or []
    if matches:
        story.append(_subheading("Evidence-to-Source Matches", styles))
        story.append(
            _rows_table(
                _limit_rows(matches, 8),
                ["Signal Category", "Evidence Summary", "Primary Source", "Reviewer Use"],
                styles,
                Table,
                TableStyle,
                colors,
                [1.25, 2.35, 1.0, 1.7],
            )
        )
    return story


def _deficiency_section(worksheet, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["deficiencies"], styles, label)
    rows = _worksheet_item(worksheet, "Deficiency Tracker")
    story.append(
        _rows_table(
            _limit_rows(rows, 12),
            ["Discipline", "Issue", "Severity", "Information Request Wording", "Resolution"],
            styles,
            Table,
            TableStyle,
            colors,
            [0.85, 1.55, 0.65, 2.5, 0.75],
        )
    )
    return story


def _integrated_section(worksheet, styles, label, Table, TableStyle, colors) -> list:
    integrated = _worksheet_item(worksheet, "Integrated Assessment")
    final_language = _worksheet_item(worksheet, "Final Review Language")
    language = "ko" if _is_ko(label) else "en"
    story = _section(label["integrated"], styles, label)
    story.append(
        _key_value_table(
            [
                (label["recommendation"], integrated.get("Recommended Action")),
                (label["key_issues"], integrated.get("Key Review Issues")),
                (label["residual_uncertainty"], integrated.get("Residual Uncertainty")),
                (label["rationale"], integrated.get("Rationale")),
            ],
            styles,
            Table,
            TableStyle,
            colors,
        )
    )
    if final_language:
        story.append(_subheading("Final Review Language", styles))
        story.append(_para(_report_text(final_language, language), styles["Body"]))
    return story


def _appendix_section(payload, styles, label, Table, TableStyle, colors) -> list:
    story = _section(label["appendix"], styles, label)
    signal_details = payload.get("signal_details") or {}
    if isinstance(signal_details, dict) and any(signal_details.values()):
        for key, title in [
            ("specifications", "Detailed Specification Evidence"),
            ("test_methods", "Detailed Test Method Evidence"),
            ("bioequivalence", "Detailed Bioequivalence Evidence"),
            ("stability", "Detailed Stability Evidence"),
            ("compounds", "Detailed Compound Evidence"),
        ]:
            rows = signal_details.get(key) or []
            if not rows:
                continue
            story.append(_subheading(title, styles))
            display_rows = []
            for row in rows[:10]:
                display_rows.append(
                    {
                        "Page": row.get("Page", "N/A"),
                        "Evidence Role": row.get("Evidence Role", ""),
                        "Evidence Summary": row.get("Evidence", ""),
                        "CTD Mapping": row.get("CTD Mapping", ""),
                    }
                )
            story.append(
                _rows_table(
                    display_rows,
                    ["Page", "Evidence Role", "Evidence Summary", "CTD Mapping"],
                    styles,
                    Table,
                    TableStyle,
                    colors,
                    [0.45, 1.2, 3.5, 1.15],
                )
            )
    for title, items in [
        ("Specifications", payload.get("specifications")),
        ("Test Methods", payload.get("test_methods")),
        ("Bioequivalence", payload.get("bioequivalence")),
        ("Stability", payload.get("stability")),
    ]:
        if items:
            story.append(_subheading(title, styles))
            story.append(_bullet_list(items, styles, label, limit=18))
    return story


def _rows_table(rows, columns, styles, Table, TableStyle, colors, widths=None):
    rows = rows or []
    if not rows:
        return _para("-", styles["Body"])
    columns = columns or _preferred_columns(rows, [])
    language = "ko" if _is_ko_style(styles) else "en"
    data = [[_para(_report_column_label(col, language), styles["TableHead"]) for col in columns]]
    for row in rows:
        data.append([_para(_report_text(_value_for_column(row, col), language, 260), styles["TableCell"]) for col in columns])
    total_width = 7.0 * 72
    if widths:
        col_widths = [unit / sum(widths) * total_width for unit in widths]
    else:
        col_widths = [total_width / len(columns)] * len(columns)
    table = Table(data, colWidths=col_widths, repeatRows=1, splitByRow=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#155E75")),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D5DEE8")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
            ]
        )
    )
    return table


def _key_value_table(pairs, styles, Table, TableStyle, colors):
    language = "ko" if _is_ko_style(styles) else "en"
    rows = []
    for key, value in pairs:
        if value is None or value == "":
            value = "TBD"
        rows.append(
            [
                _para(_report_column_label(str(key), language), styles["Key"]),
                _para(_report_text(value, language, 420), styles["TableCell"]),
            ]
        )
    table = Table(rows, colWidths=[1.7 * 72, 4.9 * 72])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EEF4F7")),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D5DEE8")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _bullet_list(items, styles, label, limit=8):
    from reportlab.platypus import Paragraph

    items = items or []
    if isinstance(items, str):
        items = [items]
    if not items:
        return _para(label["not_detected"], styles["Body"])
    language = "ko" if _is_ko(label) else "en"
    text = "<br/>".join(f"• {_safe(_report_text(item, language, 360))}" for item in items[:limit])
    if len(items) > limit:
        text += f"<br/>• ... +{len(items) - limit}"
    return Paragraph(text, styles["Body"])


def _draw_header_footer(canvas, doc_obj, label, colors, font_name, bold_font):
    canvas.saveState()
    width, height = letter_size()
    canvas.setFillColor(colors.HexColor("#102033"))
    canvas.rect(0, height - 34, width, 34, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont(bold_font, 9)
    canvas.drawString(44, height - 21, "TG")
    canvas.setFont(font_name, 8)
    canvas.drawString(72, height - 21, label["title"])
    canvas.setFont(font_name, 7)
    canvas.drawRightString(width - 44, height - 21, label["confidential"])
    canvas.setFillColor(colors.HexColor("#667085"))
    canvas.setFont(font_name, 7)
    canvas.drawString(44, 28, label["disclaimer"][:110])
    canvas.drawRightString(width - 44, 28, f"{doc_obj.page}")
    canvas.restoreState()


def _draw_cover_footer(canvas, doc_obj, label, colors, font_name):
    canvas.saveState()
    width, _ = letter_size()
    canvas.setFillColor(colors.HexColor("#667085"))
    canvas.setFont(font_name, 7)
    canvas.drawString(44, 28, label["disclaimer"][:110])
    canvas.drawRightString(width - 44, 28, "1")
    canvas.restoreState()


def letter_size():
    return 612, 792


def _subheading(title, styles):
    return _para(title, styles["Subsection"])


def _rule():
    from reportlab.platypus import HRFlowable
    from reportlab.lib import colors

    return HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#C9D4DF"), spaceAfter=5)


def _para(value, style):
    from reportlab.platypus import Paragraph

    return Paragraph(_safe(value), style)


def _safe(value) -> str:
    return escape(_clean_text(value, 1800)).replace("\n", "<br/>")


def _localize(value, language: str):
    if value is None:
        return value
    if language != "ko":
        return _english_display_value(value)
    if isinstance(value, str):
        text = value
        for source, target in COMMON_KO_TERMS.items():
            text = text.replace(source, target)
        return _dedupe_slash_duplicates(text)
    return value


def _dedupe_slash_duplicates(value: str) -> str:
    parts = [part.strip() for part in re.split(r"\s*/\s*", value or "") if part.strip()]
    if len(parts) == 2 and parts[0] == parts[1]:
        return parts[0]
    return value


def _report_text(value, language: str, limit: int = 500) -> str:
    text = _clean_text(_localize(value, language), limit)
    if language == "en":
        text = _strip_hangul_for_english(text)
    return text


def _report_column_label(value: str, language: str) -> str:
    if language == "ko":
        return str(value)
    label = REPORT_COLUMN_LABELS.get(str(value), _english_display_value(str(value)))
    return _strip_hangul_for_english(_clean_text(label, 120))


def _english_display_value(value):
    if not isinstance(value, str):
        return value
    if not re.search(r"[가-힣]", value):
        return value
    parts = [part.strip() for part in re.split(r"\s*/\s*", value) if part.strip()]
    english_parts = [part for part in parts if not re.search(r"[가-힣]", part)]
    if english_parts:
        return english_parts[0]
    return _strip_hangul_for_english(value)


def _strip_hangul_for_english(value: str) -> str:
    text = re.sub(r"[가-힣]+", "", str(value or ""))
    text = re.sub(r"\s+", " ", text).strip(" /-;:,.")
    if re.search(r"[A-Za-z0-9]", text):
        return text
    return "Korean source text omitted in English report; verify source document."


def _signal_interpretation(category: str, rows: list[dict], label: dict) -> str:
    if not rows:
        return label["gap"]
    direct = sum(1 for row in rows if "Direct" in str(row.get("Evidence Role", "")))
    rationale = sum(1 for row in rows if "Rationale" in str(row.get("Evidence Role", "")))
    if _is_ko(label):
        return f"{len(rows)}개 근거 감지; 직접 근거 {direct}개, 개발/보조 근거 {rationale}개."
    return f"{len(rows)} evidence item(s); {direct} direct, {rationale} development/supporting rationale."


def _is_ko_style(styles: dict) -> bool:
    return "ToxiKorean" in getattr(styles["Body"], "fontName", "") or "HYS" in getattr(styles["Body"], "fontName", "")


def _clean_text(value, limit: int = 500) -> str:
    if isinstance(value, dict):
        value = "; ".join(f"{k}: {v}" for k, v in value.items())
    elif isinstance(value, (list, tuple)):
        value = "; ".join(str(item) for item in value)
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    text = text.replace("{'", "").replace("'}", "")
    if len(text) > limit:
        return text[: limit - 3].rstrip() + "..."
    return text


def _limit_rows(rows, limit):
    if isinstance(rows, dict):
        rows = [rows]
    return list(rows or [])[:limit]


def _preferred_columns(rows, preferred):
    if preferred:
        available = []
        if rows:
            keys = set().union(*(row.keys() for row in rows if isinstance(row, dict)))
            available = [col for col in preferred if col in keys]
        if available:
            return available
    if rows and isinstance(rows[0], dict):
        return list(rows[0].keys())[:5]
    return ["Value"]


def _value_for_column(row, col):
    if isinstance(row, dict):
        return row.get(col, "")
    return row


def _worksheet_item(worksheet, key):
    if not isinstance(worksheet, dict):
        return {} if key != "Final Review Language" else ""
    value = worksheet.get(key)
    if value is None:
        return {} if key != "Final Review Language" else ""
    return value


def _normalize_basic_rows(rows, label):
    normalized = []
    for row in rows or []:
        normalized.append(
            {
                "항목" if _is_ko(label) else "Field": _localize(row.get("Field", ""), "ko" if _is_ko(label) else "en"),
                "값" if _is_ko(label) else "Value": _localize(row.get("Value", ""), "ko" if _is_ko(label) else "en"),
                label["reviewer_check"]: row.get("Reviewer Check", ""),
            }
        )
    return normalized


def _rename_rows(rows, mapping: dict, ko: bool):
    if not ko:
        return rows
    renamed = []
    for row in rows or []:
        renamed.append({target: _localize(row.get(source, ""), "ko") for source, target in mapping.items()})
    return renamed


def _is_ko(label):
    return label["title"].startswith("CTD 품질")


def _minimal_pdf_stub(payload: dict) -> bytes:
    body = " | ".join(f"{key}: {value}" for key, value in payload.items())
    stream = f"BT /F1 10 Tf 40 750 Td (ToxiGuard-Platform Ver.1) Tj 0 -20 Td ({body[:220]}) Tj ET"
    stream_bytes = stream.encode("latin-1", errors="replace")
    return (
        b"%PDF-1.4\n"
        b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\n"
        b"4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n"
        + f"5 0 obj<</Length {len(stream_bytes)}>>\nstream\n".encode("latin-1")
        + stream_bytes
        + b"\nendstream\nendobj\ntrailer<</Root 1 0 R>>\n%%EOF"
    )
