[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#ef4444"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#18212f"
